name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt actuel
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Étape 3 : Installer les dépendances
      - name: Install Dependencies
        run: npm install

      # Étape 4 : Lancer linting
      - name: Run Lint
        run: npm run lint
